version: '3'
services:
  web:
    build: .
    ports:
      - "1338:1337"
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: auth
